# Generated by Django 5.0.6 on 2024-07-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                ("country_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "country_name",
                    models.CharField(blank=True, max_length=50, unique=True),
                ),
            ],
        ),
    ]
