# Generated by Django 5.0.6 on 2024-07-10 19:02

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("country", "0001_initial"),
        ("tourist_detail", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TravelInfo",
            fields=[
                ("travel_id", models.AutoField(primary_key=True, serialize=True)),
                ("year", models.DateField()),
                ("hotel", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "transportation",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=40),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                ("total_duration", models.CharField()),
                ("total_cost", models.IntegerField(blank=True, null=True)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("EUR", "EUR"),
                            ("USD", "USD"),
                            ("CHF", "CHF"),
                            ("GBP", "GBP"),
                            ("other", "other"),
                        ],
                        default="EUR",
                        max_length=5,
                    ),
                ),
                (
                    "trip_type",
                    models.CharField(
                        choices=[
                            ("Vacation", "Vacation"),
                            ("Business", "Business"),
                            ("Personal", "Personal"),
                            ("other", "other"),
                        ],
                        default="Vacation",
                        max_length=15,
                    ),
                ),
                (
                    "preferred_language",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="country.country",
                    ),
                ),
                (
                    "tourist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tourist_detail.touristdetails",
                    ),
                ),
            ],
        ),
    ]
