# Generated by Django 5.0.6 on 2024-07-10 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("travel_info", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="travelinfo",
            old_name="year",
            new_name="date",
        ),
    ]
