# Generated by Django 5.0.6 on 2024-07-21 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("city", "0001_initial"),
        ("travel_info", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SatisfactionLevel",
            fields=[
                (
                    "satisfaction_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "satisfaction_value",
                    models.CharField(
                        choices=[
                            ("Very Unsatisfied", "Very Unsatisfied"),
                            ("Unsatisfied", "Unsatified"),
                            ("Neutral", "Neutral"),
                            ("Satisfied", "Satisfied"),
                            ("Very Satisfied", "Very Satisfied"),
                        ],
                        default="Neutral",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="travelinfo",
            old_name="year",
            new_name="date",
        ),
        migrations.RenameField(
            model_name="travelinfo",
            old_name="tourist",
            new_name="tourist_id",
        ),
        migrations.AddField(
            model_name="travelinfo",
            name="Rating",
            field=models.CharField(
                choices=[
                    ("1 Star", "1 Star"),
                    ("2 Stars", "2 Stars"),
                    ("3 Stars", "3 Stars"),
                    ("4 Stars", "4 Stars"),
                    ("5 Stars", "5 Stars"),
                ],
                default="1",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="travelinfo",
            name="city",
            field=models.ForeignKey(
                default="1", on_delete=django.db.models.deletion.CASCADE, to="city.city"
            ),
        ),
        migrations.AlterField(
            model_name="travelinfo",
            name="total_duration",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="travelinfo",
            name="travel_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
