# Generated by Django 5.0.6 on 2024-07-21 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("travel_info", "0003_rename_tourist_id_travelinfo_tourist"),
    ]

    operations = [
        migrations.RenameField(
            model_name="travelinfo",
            old_name="tourist",
            new_name="first_name",
        ),
    ]
