# Generated by Django 5.0.6 on 2024-07-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel_info", "0004_rename_tourist_travelinfo_first_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="travelinfo",
            options={
                "default_related_name": "%(app_label)s_%(model_name)s",
                "ordering": ("first_name",),
            },
        ),
        migrations.AddField(
            model_name="travelinfo",
            name="satisfaction_level",
            field=models.ManyToManyField(to="travel_info.satisfactionlevel"),
        ),
    ]
