# Generated by Django 5.0.6 on 2024-07-23 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("travel_info", "0005_alter_travelinfo_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="travelinfo",
            options={
                "default_related_name": "%(app_label)s_%(model_name)s",
                "ordering": ("first_name",),
                "verbose_name": "Travel Info",
                "verbose_name_plural": "Travel Infos",
            },
        ),
        migrations.RenameField(
            model_name="travelinfo",
            old_name="Rating",
            new_name="rating",
        ),
    ]
