# Generated by Django 5.0.6 on 2024-07-23 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("city", "0001_initial"),
        ("country", "0001_initial"),
        ("tourist_detail", "0004_alter_touristdetails_options"),
        ("travel_info", "0006_alter_travelinfo_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="travelinfo",
            name="city",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="travel_infos",
                to="city.city",
            ),
        ),
        migrations.AlterField(
            model_name="travelinfo",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="travel_infos",
                to="country.country",
            ),
        ),
        migrations.AlterField(
            model_name="travelinfo",
            name="first_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="travel_infos",
                to="tourist_detail.touristdetails",
            ),
        ),
        migrations.AlterField(
            model_name="travelinfo",
            name="total_duration",
            field=models.CharField(
                choices=[
                    ("1-3 days", "1-3 days"),
                    ("4-7 days", "4-7 days"),
                    ("1-2 weeks", "1-2 weeks"),
                    ("2-4 weeks", "2-4 weeks"),
                    ("1-3 months", "1-3 months"),
                    ("3-6 months", "3-6 months"),
                    ("6-12 months", "6-12 months"),
                    ("more than a year", "More than a year"),
                ],
                default="1-3 days",
                max_length=20,
            ),
        ),
    ]
