# Generated by Django 5.0.6 on 2024-07-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel_info", "0007_alter_travelinfo_city_alter_travelinfo_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="travelinfo",
            name="total_duration",
            field=models.CharField(
                choices=[
                    ("1-3 days", "1-3 days"),
                    ("4-7 days", "4-7 days"),
                    ("1-2 weeks", "1-2 weeks"),
                    ("2-4 weeks", "2-4 weeks"),
                    ("1-3 months", "1-3 months"),
                    ("3-6 months", "3-6 months"),
                    ("6-12 months", "6-12 months"),
                    ("more than a year", "More than a year"),
                ],
                default="1-3 days",
                max_length=20,
            ),
        ),
    ]
