# Generated by Django 5.0.6 on 2024-07-10 18:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TouristDetails",
            fields=[
                ("tourist_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=40)),
                ("last_name", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=15,
                        null=True,
                    ),
                ),
                ("age", models.SmallIntegerField(blank=True, null=True)),
                ("occupation", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "nationality",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "language",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=20),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
            ],
        ),
    ]
