# Generated by Django 5.0.6 on 2024-07-21 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tourist_detail", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="touristdetails",
            old_name="tourist_id",
            new_name="tourist",
        ),
    ]
