# Generated by Django 5.0.6 on 2024-07-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tourist_detail", "0002_rename_tourist_id_touristdetails_tourist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="touristdetails",
            name="tourist",
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
