# Generated by Django 5.0.6 on 2024-07-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Rating",
            fields=[
                ("rating_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "rating_value",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1 Star", "1 Star"),
                            ("2 Stars", "2 Stars"),
                            ("3 Stars", "3 Stars"),
                            ("4 Stars", "4 Stars"),
                            ("5 Stars", "5 Stars"),
                        ],
                        default="Neutral",
                        max_length=50,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
